import { routeTree as baseRouteTree } from '@tanstack/react-router'
import { rootRoute } from './__root'

// Route imports - these will be auto-generated by TanStack Router
// For now, we manually define the route tree

export const routeTree = rootRoute.addChildren([
  // Routes will be added here as we migrate them
])
